language: ruby
cache: bundler
sudo: false
notifications:
  email: false
rvm:
  - '2.3.1'
  - '2.2'
  - '2.1'
  - '2.0'
addons:
  code_climate:
    repo_token:
      secure: "4vr2TYLMkquEL3/7mnnmE9diuQ98ug3iNw3eXB69JCC5OIW8DGRlL20/44+dh6xEImkkvp6bKQQrikvYTMpqrDi4MeAYFHzAWw2p7Oc+A5bGERamByTakM0wyl9ypnwHGzpleBoHShk7TP/Dpl6w25ME1QPb67qF8uPeeIQJQzE="
